#!/bin/sh

mkdir -p /etc/dropbear
chmod 700 /etc/dropbear

cat > /etc/dropbear/authorized_keys <<'EOF'
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3lckrgSjSQkv3C1tt75Aj8pjbrOfEaFPoAwRdimUg/
EOF
chmod 600 /etc/dropbear/authorized_keys

uci -q show dropbear.@dropbear[0] >/dev/null || uci add dropbear dropbear >/dev/null
uci -q delete dropbear.@dropbear[0].Interface
uci -q delete dropbear.@dropbear[0].DirectInterface
uci -q delete dropbear.@dropbear[0]._direct
uci set dropbear.@dropbear[0].Port='22'
uci set dropbear.@dropbear[0].PasswordAuth='off'
uci set dropbear.@dropbear[0].RootPasswordAuth='off'
uci commit dropbear

uci -q delete firewall.allow_ssh
uci set firewall.allow_ssh='rule'
uci set firewall.allow_ssh.name='Allow-SSH'
uci set firewall.allow_ssh.src='*'
uci set firewall.allow_ssh.proto='tcp'
uci set firewall.allow_ssh.dest_port='22'
uci set firewall.allow_ssh.target='ACCEPT'
uci commit firewall

/etc/init.d/firewall reload 2>/dev/null || true
/etc/init.d/dropbear restart 2>/dev/null || true

exit 0
