#!/bin/sh

for device in $(uci -q show network | sed -n "s/^network\.\([^=]*\)=device$/\1/p"); do
	[ "$(uci -q get network."$device".name)" = "br-lan" ] || continue
	uci del_list network."$device".ports='eth0' 2>/dev/null || true
	break
done

uci set network.wan='interface'
uci set network.wan.device='eth0'
uci set network.wan.proto='dhcp'
uci set network.wan.hostname='Unknown'

uci set network.wan6='interface'
uci set network.wan6.device='eth0'
uci set network.wan6.proto='dhcpv6'
uci set network.wan6.reqaddress='try'
uci set network.wan6.reqprefix='auto'

uci commit network

exit 0
